version: '3.7'

services:
  # PHP-FPM - Service
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile

    container_name: app
    depends_on:
      - db
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    networks:
      - app-network


  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
    - '3306:3306'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - app-network


  # NGINX - Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "8443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network


# Networks
networks:
  app-network:
    driver: bridge
